name: AI News Bot

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-news-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run news bot
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_GROUP_CHAT_ID }}
      run: python news_bot.py